import { useCallback, useRef, useState } from 'react';
import { ScrollView, View, Text, Pressable, ActivityIndicator, Alert, Modal } from 'react-native';
import { CameraView, useCameraPermissions } from 'expo-camera';
import * as Location from 'expo-location';
import { Ionicons } from '@expo/vector-icons';
import { Banner } from '../../src/components/Banner';
import { OfflineNotice } from '../../src/components/OfflineNotice';
import { Button } from '../../src/components/Button';
import { Card } from '../../src/components/Card';
import { ErrorState, LoadingState } from '../../src/components/ErrorState';
import { TopBar } from '../../src/components/TopBar';
import { colors } from '../../src/constants/colors';
import { apiGet, apiPost, ApiError } from '../../src/services/api';
import { endpoints } from '../../src/services/endpoints';
import { useDtr } from '../../src/hooks/useDtr';
import { formatDate, formatTime } from '../../src/lib/datetime';
import { DtrPunchResult, DtrScanPreview, DtrSession } from '../../src/types/api';

/**
 * The QR encodes the web SPA's own landing URL —
 * `{FRONTEND_URL}/student/dtr/scan?s={32-char token}` (see
 * Supervisor\DtrGeofenceController::qrPayload). The same physical code
 * therefore serves the browser and this app; mobile just lifts the token out
 * rather than opening a browser.
 *
 * Accepts a bare 32-char token too, so a code generated by any future
 * payload format that drops the URL wrapper still scans.
 */
function extractSiteToken(raw: string): string | null {
  const value = raw.trim();

  const fromQuery = value.match(/[?&]s=([A-Za-z0-9]{32})(?:&|$)/);
  if (fromQuery) return fromQuery[1];

  if (/^[A-Za-z0-9]{32}$/.test(value)) return value;

  return null;
}

function formatHours(minutes: number | null) {
  if (minutes === null) return '—';
  const h = Math.floor(minutes / 60);
  const m = minutes % 60;
  return h > 0 ? `${h}h ${m}m` : `${m}m`;
}

const NEXT_ACTION_LABEL: Record<DtrScanPreview['next_action'], string> = {
  clock_in: 'Clock In',
  clock_out: 'Clock Out',
  blocked_other_site: 'Blocked',
};

export default function Scan() {
  const { data, loading, error, isOffline, reload } = useDtr();
  const [permission, requestPermission] = useCameraPermissions();

  const [cameraOpen, setCameraOpen] = useState(false);
  const [resolving, setResolving] = useState(false);
  const [preview, setPreview] = useState<DtrScanPreview | null>(null);
  const [token, setToken] = useState<string | null>(null);
  const [punching, setPunching] = useState(false);
  // A CameraView fires onBarcodeScanned continuously while a code is in frame,
  // so without a latch one scan becomes dozens of API calls.
  const scanLatch = useRef(false);

  const closeCamera = useCallback(() => {
    setCameraOpen(false);
    scanLatch.current = false;
  }, []);

  async function openCamera() {
    if (!permission?.granted) {
      const result = await requestPermission();
      if (!result.granted) {
        Alert.alert(
          'Camera access needed',
          'InternTrack needs the camera to read your workplace QR code. You can enable it in Settings.'
        );
        return;
      }
    }
    scanLatch.current = false;
    setPreview(null);
    setToken(null);
    setCameraOpen(true);
  }

  async function onBarcodeScanned(result: { data: string }) {
    if (scanLatch.current) return;
    scanLatch.current = true;

    const siteToken = extractSiteToken(result.data);
    if (!siteToken) {
      closeCamera();
      Alert.alert(
        "That's not an InternTrack code",
        'Scan the Daily Time Record QR code shown by your supervisor.'
      );
      return;
    }

    setCameraOpen(false);
    setResolving(true);
    try {
      // Coordinate-free preview FIRST, deliberately: a student who scanned the
      // wrong code — or whose phone is signed in as someone else — finds out
      // before granting a location permission or writing anything.
      const res = await apiGet<DtrScanPreview>(endpoints.dtrScan, { site_token: siteToken });
      setPreview(res);
      setToken(siteToken);
    } catch (err) {
      const apiErr = err as ApiError;
      Alert.alert(
        apiErr.status === null ? 'You appear to be offline' : 'Could not read that code',
        apiErr.status === null
          ? 'A clock-in records where and when you were, so it needs a live connection. Try again once you have signal.'
          : apiErr.message
      );
    } finally {
      setResolving(false);
      scanLatch.current = false;
    }
  }

  async function confirmPunch() {
    if (!token || !preview) return;

    const permissionResult = await Location.requestForegroundPermissionsAsync();
    if (!permissionResult.granted) {
      Alert.alert(
        'Location access needed',
        'Your clock-in is recorded against the workplace location, so InternTrack needs your position to accept it.'
      );
      return;
    }

    setPunching(true);
    try {
      const position = await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.High });
      const res = await apiPost<DtrPunchResult>(endpoints.dtrPunch, {
        site_token: token,
        latitude: position.coords.latitude,
        longitude: position.coords.longitude,
        accuracy: position.coords.accuracy ?? undefined,
      });

      setPreview(null);
      setToken(null);
      await reload();

      Alert.alert(
        res.action === 'clocked_in' ? 'Clocked in' : 'Clocked out',
        // The server's own message already covers the auto-close case, so
        // there is exactly one wording for it rather than two that could drift.
        `${res.message}\n\nRecorded for ${res.student_name}, ${res.distance_meters}m from the registered point.`
      );
    } catch (err) {
      const apiErr = err as ApiError;
      Alert.alert(
        apiErr.status === null ? 'You appear to be offline' : 'Could not record that punch',
        apiErr.status === null
          ? // Deliberately NOT queued like a journal entry: a journal is the
            // student's own words and is just as true an hour later, but a
            // punch is a claim about where they were at a moment in time.
            // Sending it later would record a time and place nobody observed.
            'A clock-in has to be recorded at the moment it happens, so it cannot be saved for later. Try again once you have signal, or ask your supervisor to adjust the session.'
          : apiErr.message
      );
    } finally {
      setPunching(false);
    }
  }

  if (loading && !data) return <LoadingState />;
  if (error && !data) return <ErrorState message={error.message} onRetry={reload} />;
  if (!data) return null;

  if (!data.enabled) {
    return (
      <View style={{ flex: 1, backgroundColor: colors.gray50 }}>
        <TopBar />
        <Banner variant="info">{data.message}</Banner>
      </View>
    );
  }

  const open = data.open_session;

  return (
    <View style={{ flex: 1, backgroundColor: colors.gray50 }}>
      <TopBar />

      <ScrollView contentContainerStyle={{ paddingBottom: 32 }}>
        {/* Was a hardcoded `neutral` banner — grey on grey, and it bypassed
            OfflineNotice entirely, so this screen kept the quiet treatment
            after every other screen got the loud one. It matters MOST here:
            the DTR is the app's one online_only feature, so offline the
            button genuinely cannot work, and a student standing at the door
            needs to see that rather than tap a dead control. */}
        <OfflineNotice feature="dtr" show={isOffline} />

        {open ? (
          <Banner variant="info">
            You're clocked in at {open.site ?? 'your site'} since {formatTime(open.time_in)}. Scan the same code again
            when you leave.
          </Banner>
        ) : null}

        <View style={{ alignItems: 'center', marginTop: 24, paddingHorizontal: 20 }}>
          <Button
            label={open ? 'Scan to Clock Out' : 'Scan to Clock In'}
            icon="qr-code-outline"
            loading={resolving}
            disabled={resolving || isOffline}
            onPress={openCamera}
            style={{ width: '100%', paddingVertical: 18 }}
          />
          <Text style={{ fontSize: 11.5, color: colors.gray500, marginTop: 10, textAlign: 'center' }}>
            Scan the Daily Time Record code shown by your supervisor.
          </Text>
        </View>

        <Card title="Hours Progress">
          <View style={{ flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 }}>
            <Text style={{ fontSize: 26, fontWeight: '700', color: colors.black }}>
              {data.progress.hours_completed}
              <Text style={{ fontSize: 13, fontWeight: '500', color: colors.gray500 }}>
                {' '}
                / {data.progress.hours_required} hrs
              </Text>
            </Text>
            <Text style={{ fontSize: 13, fontWeight: '600', color: colors.blue600, alignSelf: 'flex-end' }}>
              {/* Null percent means the batch has no required_hours — render a
                  dash rather than inventing a denominator. */}
              {data.progress.hours_percent === null ? '—' : `${data.progress.hours_percent}%`}
            </Text>
          </View>
          <View style={{ height: 8, borderRadius: 4, backgroundColor: colors.gray200, overflow: 'hidden' }}>
            {data.progress.hours_percent !== null && data.progress.hours_percent > 0 ? (
              <View
                style={{
                  width: `${data.progress.hours_percent}%`,
                  height: '100%',
                  borderRadius: 4,
                  backgroundColor: colors.blue600,
                }}
              />
            ) : null}
          </View>
          <Text style={{ fontSize: 11.5, color: colors.gray500, marginTop: 10 }}>
            This week: {formatHours(data.week.minutes)}
            {data.company ? ` · ${data.company}` : ''}
          </Text>
        </Card>

        <Card title="This Week's Sessions">
          {data.sessions.length === 0 ? (
            <Text style={{ fontSize: 12.5, color: colors.gray500 }}>No sessions recorded this week yet.</Text>
          ) : (
            data.sessions.map((session: DtrSession) => (
              <View
                key={session.id}
                style={{
                  flexDirection: 'row',
                  alignItems: 'center',
                  justifyContent: 'space-between',
                  paddingVertical: 10,
                  borderTopWidth: 1,
                  borderTopColor: colors.gray100,
                }}
              >
                <View style={{ flex: 1, paddingRight: 10 }}>
                  <Text style={{ fontSize: 12.5, fontWeight: '600', color: colors.black }}>
                    {session.work_date ? formatDate(session.work_date, { month: 'short', day: 'numeric' }) : '—'}
                  </Text>
                  <Text style={{ fontSize: 11, color: colors.gray500, marginTop: 2 }}>
                    {formatTime(session.time_in)} – {session.time_out ? formatTime(session.time_out) : 'open'}
                    {session.site ? ` · ${session.site}` : ''}
                  </Text>
                  {/* Surfaced so a student can see WHY a session isn't
                      counting rather than silently wondering. */}
                  {session.adjustment_reason ? (
                    /* Amber text alone read as a caption. This says a
                       supervisor changed the row, which is the one line on a
                       session a student may need to query. */
                    <View
                      style={{
                        flexDirection: 'row',
                        alignItems: 'center',
                        gap: 5,
                        alignSelf: 'flex-start',
                        backgroundColor: colors.warnBg,
                        borderWidth: 1,
                        borderColor: colors.warnBorder,
                        borderRadius: 7,
                        paddingHorizontal: 7,
                        paddingVertical: 4,
                        marginTop: 5,
                      }}
                    >
                      <Ionicons name="warning" size={11} color={colors.warnTx} />
                      <Text style={{ flex: 1, fontSize: 10.5, color: colors.warnTx, lineHeight: 14 }}>
                        {session.adjustment_reason}
                      </Text>
                    </View>
                  ) : null}
                </View>
                <Text style={{ fontSize: 12.5, fontWeight: '600', color: colors.gray600 }}>
                  {formatHours(session.minutes_worked)}
                </Text>
              </View>
            ))
          )}
        </Card>
      </ScrollView>

      {/* --- Camera --- */}
      <Modal visible={cameraOpen} animationType="slide" onRequestClose={closeCamera}>
        <View style={{ flex: 1, backgroundColor: 'black' }}>
          <CameraView
            style={{ flex: 1 }}
            facing="back"
            barcodeScannerSettings={{ barcodeTypes: ['qr'] }}
            onBarcodeScanned={onBarcodeScanned}
          />
          <View style={{ position: 'absolute', top: 60, left: 0, right: 0, alignItems: 'center' }}>
            <Text style={{ color: 'white', fontSize: 14, fontWeight: '600' }}>
              Point at the Daily Time Record code
            </Text>
          </View>
          <Button
            label="Cancel"
            variant="secondary"
            onPress={closeCamera}
            style={{ position: 'absolute', bottom: 48, alignSelf: 'center', paddingHorizontal: 32 }}
          />
        </View>
      </Modal>

      {/* --- Confirmation, shown BEFORE any location is requested --- */}
      <Modal visible={preview !== null} transparent animationType="fade" onRequestClose={() => setPreview(null)}>
        <View style={{ flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', padding: 24 }}>
          <View style={{ backgroundColor: colors.white, borderRadius: 16, padding: 20 }}>
            {preview ? (
              <>
                <Text style={{ fontSize: 16, fontWeight: '700', color: colors.black, marginBottom: 4 }}>
                  {preview.site.label}
                </Text>
                <Text style={{ fontSize: 12.5, color: colors.gray500, marginBottom: 14 }}>
                  {preview.site.company ?? 'Your host company'}
                </Text>

                {/* Naming the account is what makes a wrong-phone punch
                    visible BEFORE anything is written — a scan looks identical
                    either way. */}
                <View
                  style={{
                    backgroundColor: colors.gray100,
                    borderRadius: 10,
                    padding: 12,
                    marginBottom: 14,
                  }}
                >
                  <Text style={{ fontSize: 11, color: colors.gray500 }}>Recording for</Text>
                  <Text style={{ fontSize: 13.5, fontWeight: '600', color: colors.black, marginTop: 2 }}>
                    {preview.student.name}
                  </Text>
                  {preview.student.student_id_number ? (
                    <Text style={{ fontSize: 11.5, color: colors.gray500, marginTop: 1 }}>
                      {preview.student.student_id_number}
                    </Text>
                  ) : null}
                </View>

                {preview.next_action === 'blocked_other_site' ? (
                  /* This is the one thing on the card that STOPS the punch, and
                     it used to be a plain red paragraph sitting where the
                     neutral explainer otherwise sits — the same size, the same
                     position, no icon. Given the Clock In button below is also
                     disabled, a student had nothing telling them why. */
                  <View
                    style={{
                      flexDirection: 'row',
                      gap: 9,
                      backgroundColor: colors.redBg,
                      borderWidth: 1,
                      borderColor: '#fecaca',
                      borderLeftWidth: 5,
                      borderLeftColor: colors.redDark,
                      borderRadius: 10,
                      padding: 11,
                      marginBottom: 14,
                    }}
                  >
                    <View
                      style={{
                        width: 22,
                        height: 22,
                        borderRadius: 11,
                        backgroundColor: colors.redDark,
                        alignItems: 'center',
                        justifyContent: 'center',
                      }}
                    >
                      <Ionicons name="alert" size={14} color={colors.white} />
                    </View>
                    <View style={{ flex: 1 }}>
                      <Text style={{ fontSize: 12.5, fontWeight: '700', color: colors.redTx, marginBottom: 2 }}>
                        Open session at another site
                      </Text>
                      <Text style={{ fontSize: 11.5, color: colors.redTx, lineHeight: 16 }}>
                        Clock out there first, or ask your supervisor to close it.
                      </Text>
                    </View>
                  </View>
                ) : (
                  <Text style={{ fontSize: 12, color: colors.gray500, marginBottom: 14, lineHeight: 17 }}>
                    Your location is checked against this site (within {preview.site.radius_meters}m) and recorded with
                    the punch.
                  </Text>
                )}

                <View style={{ flexDirection: 'row', gap: 10 }}>
                  <Button
                    label="Cancel"
                    variant="secondary"
                    fullWidth
                    onPress={() => {
                      setPreview(null);
                      setToken(null);
                    }}
                  />
                  <Button
                    label={NEXT_ACTION_LABEL[preview.next_action]}
                    fullWidth
                    loading={punching}
                    disabled={punching || preview.next_action === 'blocked_other_site'}
                    onPress={confirmPunch}
                  />
                </View>
              </>
            ) : null}
          </View>
        </View>
      </Modal>
    </View>
  );
}
